### ISSUE TITLE
RuntimeError: cannot resize variables that require grad & cuda out of memory (pytorch 0.4.0)

### ISSUE THREAD

**Issue by KaiyangZhou** [zhirongw/lemniscate.pytorch#1]
Hi Zhirong,

I met the following error when running this code with pytorch 0.4.0:
```bash
  File "lib/NCEAverage.py", line 27, in forward
    x.resize_(batchSize, inputSize, 1)
RuntimeError: cannot resize variables that require grad
```
I changed `x.resize_()` to `x.data.resize_()` and the code ran normally, but the GPU memory usage rapidaly grew and finally the `RuntimeError: cuda runtime error` message came out (I used `python cifar.py --nce-k 4096 --nce-t 0.07 --lr 0.03`). Any idea of why this would happen?

Btw, `cifar.py` does not have `--arch` so the instruction command in [here](https://github.com/zhirongw/lemniscate.pytorch#usage) might need to be updated.

Thanks.

**Comment by zhirongw** [comment]
Can you try with pytorch 3.0?
Pytorch 4.0 is just released several weeks ago, and we have not tested our code on 4.0.
