### ISSUE TITLE
How long will it take to train for ResNet-50 on ImageNet-1k?

### ISSUE THREAD

**Issue by yzou2** [zhirongw/lemniscate.pytorch#14]
Hi Zhirong, thanks for your great work. Would you kindly tell me how long it will take to train for ResNet-50 on ImageNet-1k? I did not find such details on the paper.

**Comment by zhirongw** [comment]
@yzou2 It will take around 4 days if you have 4 V100 cards, and 3 days on 8 V100 cards. Runtime per iteration is similar to supervised ResNet. The training needs a bit longer (200 epochs) to converge. Training even longer helps improve the performance.

**Comment by yzou2** [comment]
Thanks a lot for your reply, Zhirong!
