### ISSUE TITLE
Question about AliasMethod

### ISSUE THREAD

**Issue by HikaruSama233** [zhirongw/lemniscate.pytorch#2]
Hi Zhirong, 

I am confused about the usage of _AliasMethod_.
In NCEAverage.py line79-80, there are
```
self.unigrams = torch.ones(self.nLem)
self.multinomial = AliasMethod(self.unigrams)
```
In my view, it means the probs for _AliasMethod_ are uniformly distributed. 
According to this page,[]( http://www.keithschwarz.com/darts-dice-coins/), the algorithm should be

> Algorithm: Simulating a Fair Die
> Generate a uniformly-random value x in the range [0,1).
> Return ⌊xn⌋.

instead of all the redundant steps.

After I ran the code line by line, I got the same conclusion.

Did I misunderstand something here?

Thank you.

**Comment by zhirongw** [comment]
Hi,

You are right. Drawing a uniform multinomial can be as simple as return  ⌊xn⌋.
The AliasMethod is flexible to draw samples from non-uniform multinomial distributions.
I borrowed the aliasmethod for the flexibility and efficiency, though I only used it for uniform distributions.
Hope it answer your question.

**Comment by HikaruSama233** [comment]
Thanks.
