### ISSUE TITLE
trouble extracting pretrained models

### ISSUE THREAD

**Issue by grez72** [zhirongw/lemniscate.pytorch#3]
Thanks for making your model available. 

I'm having some trouble extracting the pretrained models. I've downloaded these files:
http://zhirongw.westus2.cloudapp.azure.com/models/lemniscate_resnet18.pth.tar
http://zhirongw.westus2.cloudapp.azure.com/models/lemniscate_resnet50.pth.tar

But when I attempt to extract the tar files, e.g.:
tar xf lemniscate_resnet18.pth.tar

I get the following error:
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

I've tried on both a linux Ubuntu 16.04 and MAC OSX system.

Any ideas what I might be doing wrong?

**Comment by yjxiong** [comment]
You don't need to untar the files. PyTorch will load them directly.

**Comment by julycetc** [comment]
When i load the pretrained model  lemniscate_resnet50.pth.tar,I get the following error:

model=torch.load('lemniscate_resnet18.pth.tar')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 574, in _load
    result = unpickler.load()
ImportError: No module named lib.NCEAverage

The environment is quiet the same as yours,python2.7 and torch=0.4.0.Do you know why?
