### ISSUE TITLE
Failed loading module while running cifar10

### ISSUE THREAD

**Issue by guillaumejs2403** [zhirongw/lemniscate.pytorch#5]
Hello,

I was trying to run your model on cifar10 using 
```
python cifar.py --nce-k 0 --nce-t 0.1 --lr 0.03
```
and an error surged saying that alias_multinomial module didn't exist (line 4 in lib/NCEAverage.py) 
I fixed it just adding a dot before alias_multinomial
```
from .alias_multinomial import AliasMethod
```

**Comment by zhirongw** [comment]
Thanks! Fixed.
